const actionTypes = Object.freeze({
    REFRESH_STORE_SUCCESS: 'REFRESH_STORE_SUCCESS',
    REFRESH_STORE_FAILED: 'REFRESH_STORE_FAILED',

    // error:
    RESPONSE_MESSAGE: 'RESPONSE_MESSAGE',

    // login/logout
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILED: 'LOGOUT_SUCCESS',
    CHECK_PERMISSION_SUCCESS: 'CHECK_PERMISSION_SUCCESS',
    CHECK_PERMISSION_FAILED: 'CHECK_PERMISSION_FAILED',
    LOADING_SUCCESS: 'LOADING_SUCCESS',
    LOADING_FAILED: 'LOADING_FAILED',
    LOADING_PRODUCT_SUCCESS: 'LOADING_PRODUCT_SUCCESS',
    LOADING_PRODUCT_FAILED: 'LOADING_PRODUCT_FAILED',

    // register
    REGISTER: 'REGISTER',

    // send mail
    SEND_MAIL_SUCCESS: 'SEND_MAIL_SUCCESS',
    SEND_MAIL_FAILED: 'SEND_MAIL_FAILED',
    VERIFY_OTP_SUCCESS: 'VERIFY_OTP_SUCCESS',
    VERIFY_OTP_FAILED: 'VERIFY_OTP_FAILED',

    // auth
    CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
    CHANGE_PASSWORD_FAILED: 'CHANGE_PASSWORD_FAILED',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    REFRESH_STATE_AUTH: 'REFRESH_STATE_AUTH',

    // user
    CREATE_NEW_USER_SUCCESS: 'CREATE_NEW_USER_SUCCESS',
    CREATE_NEW_USER_FAILED: 'CREATE_NEW_USER_FAILED',
    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',
    GET_ALL_ADDRESS_SUCCESS: 'GET_ALL_ADDRESS_SUCCESS',
    GET_ALL_ADDRESS_FAILED: 'GET_ALL_ADDRESS_FAILED',
    GET_ALL_ROLES_SUCCESS: 'GET_ALL_ROLES_SUCCESS',
    GET_ALL_ROLES_FAILED: 'GET_ALL_ROLES_FAILED',
    DELTE_USER_SUCCESS: 'DELTE_USER_SUCCESS',
    DELTE_USER_FAILED: 'DELTE_USER_FAILED',
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',
    GET_COUNT_USERS_SUCCESS: 'GET_COUNT_USERS_SUCCESS',
    GET_COUNT_USERS_FAILED: 'GET_COUNT_USERS_FAILED',
    GET_USER_BY_ID_SUCCESS: 'GET_USER_BY_ID_SUCCESS',
    GET_USER_BY_ID_FAILED: 'GET_USER_BY_ID_FAILED',
    GET_LIMIT_USERS_SUCCESS: 'GET_LIMIT_USERS_SUCCESS',
    GET_LIMIT_USERS_FAILED: 'GET_LIMIT_USERS_FAILED',
    UPDATE_NAME_USER_SUCCESS: 'UPDATE_NAME_USER_SUCCESS',
    UPDATE_NAME_USER_FAILED: 'UPDATE_NAME_USER_FAILED',
    REFRESH_STATE_INFO_RESPONE: 'REFRESH_STATE_INFO_RESPONE',
    FIND_USER_BY_NAME_SUCCESS: 'FIND_USER_BY_NAME_SUCCESS',
    FIND_USER_BY_NAME_FAILED: 'FIND_USER_BY_NAME_FAILED',

    // category
    FETCH_ALL_CATEGORIES_SUCCESS: 'FETCH_ALL_CATEGORIES_SUCCESS',
    FETCH_ALL_CATEGORIES_FAILED: 'FETCH_ALL_CATEGORIES_FAILED',
    GET_ALL_CATEGORIES_DETAIL_SUCCESS: 'GET_ALL_CATEGORIES_DETAIL_SUCCESS',
    GET_ALL_CATEGORIES_DETAIL_FAILED: 'GET_ALL_CATEGORIES_DETAIL_FAILED',
    GET_ALL_CATEGORIES_DETAIL_BY_TYPE_SUCCESS: 'GET_ALL_CATEGORIES_DETAIL_BY_TYPE_SUCCESS',
    GET_ALL_CATEGORIES_DETAIL_BY_TYPE_FAILED: 'GET_ALL_CATEGORIES_DETAIL_BY_TYPE_FAILED',
    GET_CATEGORIES_BY_TYPE_SUCCESS: 'GET_CATEGORIES_BY_TYPE_SUCCESS',
    GET_CATEGORIES_BY_TYPE_FAILED: 'GET_CATEGORIES_BY_TYPE_FAILED',

    // product type
    REFRESH_INFO_PRODUCT_TYPE: 'REFRESH_INFO_PRODUCT_TYPE',
    GET_ALL_PRODUCT_TYPES_SUCCESS: 'GET_ALL_PRODUCT_TYPES_SUCCESS',
    GET_ALL_PRODUCT_TYPES_FAILED: 'GET_ALL_PRODUCT_TYPES_FAILED',
    GET_LIMIT_PRODUCT_TYPES_SUCCESS: 'GET_LIMIT_PRODUCT_TYPES_SUCCESS',
    GET_LIMIT_PRODUCT_TYPES_FAILED: 'GET_LIMIT_PRODUCT_TYPES_FAILED',
    GET_PRODUCT_TYPES_BY_CATEGORYID_SUCCESS: 'GET_PRODUCT_TYPES_BY_CATEGORYID_SUCCESS',
    GET_PRODUCT_TYPES_BY_CATEGORYID_FAILED: 'GET_PRODUCT_TYPES_BY_CATEGORYID_FAILED',
    GET_PRODUCT_TYPES_BY_ID_SUCCESS: 'GET_PRODUCT_TYPES_BY_ID_SUCCESS',
    GET_PRODUCT_TYPES_BY_ID_FAILED: 'GET_PRODUCT_TYPES_BY_ID_FAILED',
    CREATE_PRODUCT_TYPE: 'CREATE_PRODUCT_TYPE',

    // discount
    REFRESH_INFO_RES_DISCOUNT: 'REFRESH_INFO_RES_DISCOUNT',
    GET_ALL_DISCOUNTS_SUCCESS: 'GET_ALL_DISCOUNTS_SUCCESS',
    GET_ALL_DISCOUNTS_FAILED: 'GET_ALL_DISCOUNTS_FAILED',
    GET_LIMIT_DISCOUNT_SUCCESS: 'GET_LIMIT_DISCOUNT_SUCCESS',
    GET_LIMIT_DISCOUNT_FAILED: 'GET_LIMIT_DISCOUNT_FAILED',
    GET_DISCOUNT_BY_ID_SUCCESS: 'GET_DISCOUNT_BY_ID_SUCCESS',
    GET_DISCOUNT_BY_ID_FAILED: 'GET_DISCOUNT_BY_ID_FAILED',
    RESPONSE_INFO_DISSCOUNT: 'RESPONSE_INFO_DISSCOUNT',

    // brand
    GET_ALL_BRANDS_SUCCESS: 'GET_ALL_BRANDS_SUCCESS',
    GET_ALL_BRANDS_FAILED: 'GET_ALL_BRANDS_FAILED',

    // size
    GET_ALL_SIZES_BY_TYPE_SUCCESS: 'GET_ALL_SIZES_BY_TYPE_SUCCESS',
    GET_ALL_SIZES_BY_TYPE_FAILED: 'GET_ALL_SIZES_BY_TYPE_FAILED',

    // color
    GET_ALL_COLORS_SUCCESS: 'GET_ALL_COLORS_SUCCESS',
    GET_ALL_COLORS_FAILED: 'GET_ALL_COLORS_FAILED',

    // color
    GET_ALL_LOGOS_SUCCESS: 'GET_ALL_LOGOS_SUCCESS',
    GET_ALL_LOGOS_FAILED: 'GET_ALL_LOGOS_FAILED',

    // image
    GET_ALL_IMAGES_PRODUCT_SUCCESS: 'GET_ALL_IMAGES_PRODUCT_SUCCESS',
    GET_ALL_IMAGES_PRODUCT_FAILED: 'GET_ALL_IMAGES_PRODUCT_FAILED',
    GET_ALL_IMAGES_BY_PRODUCTID_SUCCESS: 'GET_ALL_IMAGES_BY_PRODUCTID_SUCCESS',
    GET_ALL_IMAGES_BY_PRODUCTID_FAILED: 'GET_ALL_IMAGES_BY_PRODUCTID_FAILED',
    GET_IMAGES_PRODUCT_BY_CATEGORY_SUCCESS: 'GET_IMAGES_PRODUCT_BY_CATEGORY_SUCCESS',
    GET_IMAGES_PRODUCT_BY_CATEGORY_FAILED: 'GET_IMAGES_PRODUCT_BY_CATEGORY_FAILED',
    REFRESH_INFO_RESPONSE_IMAGE: 'REFRESH_INFO_RESPONSE_IMAGE',


    // product
    REFRESH_INFO_RESPONSE_PRODUCT: 'REFRESH_INFO_RESPONSE_PRODUCT',
    FETCH_ALL_PRODUCTS_SUCCESS: 'FETCH_ALL_PRODUCTS_SUCCESS',
    FETCH_ALL_PRODUCTS_FAILED: 'FETCH_ALL_PRODUCTS_FAILED',
    GET_ALL_PRODUCTS_PUBLIC_SUCCESS: 'GET_ALL_PRODUCTS_PUBLIC_SUCCESS',
    GET_ALL_PRODUCTS_PUBLIC_FAILED: 'GET_ALL_PRODUCTS_PUBLIC_FAILED',
    CUD_PRODUCT: 'CUD_PRODUCT',
    GET_PRODUCT_BY_ID_SUCCESS: 'GET_PRODUCT_BY_ID_SUCCESS',
    GET_PRODUCT_BY_ID_FAILED: 'GET_PRODUCT_BY_ID_FAILED',
    GET_COUNT_PRODUCTS_SUCCESS: 'GET_COUNT_PRODUCTS_SUCCESS',
    GET_COUNT_PRODUCTS_FAILED: 'GET_COUNT_PRODUCTS_FAILED',
    CHANGE_IMAGE_PRODUCT: 'CHANGE_IMAGE_PRODUCT',
    FETCH_DESCRIPTION_PRODUCT_SUCCESS: 'FETCH_DESCRIPTION_PRODUCT_SUCCESS',
    FETCH_DESCRIPTION_PRODUCT_FAILED: 'FETCH_DESCRIPTION_PRODUCT_FAILED',
    ADD_DESCRIPTION_PRODUCT_SUCCESS: 'ADD_DESCRIPTION_PRODUCT_SUCCESS',
    ADD_DESCRIPTION_PRODUCT_FAILED: 'ADD_DESCRIPTION_PRODUCT_FAILED',
    GET_QUANTITY_OF_EACH_PRODUCT_BY_CATEGORY_SUCCESS: 'GET_QUANTITY_OF_EACH_PRODUCT_BY_CATEGORY_SUCCESS',
    GET_QUANTITY_OF_EACH_PRODUCT_BY_CATEGORY_FAILED: 'GET_QUANTITY_OF_EACH_PRODUCT_BY_CATEGORY_FAILED',
    GET_PRODUCT_BY_CATEGORY_SUCCESS: 'GET_PRODUCT_BY_CATEGORY_SUCCESS',
    GET_PRODUCT_BY_CATEGORY_FAILED: 'GET_PRODUCT_BY_CATEGORY_FAILED',
    GET_PRODUCT_BY_CATEGORY_LIMIT_SUCCESS: 'GET_PRODUCT_BY_CATEGORY_LIMIT_SUCCESS',
    GET_PRODUCT_BY_CATEGORY_LIMIT_FAILED: 'GET_PRODUCT_BY_CATEGORY_LIMIT_FAILED',
    GET_PRODUCT_BY_CATEGORY_DETAIL_SUCCESS: 'GET_PRODUCT_BY_CATEGORY_DETAIL_SUCCESS',
    GET_PRODUCT_BY_CATEGORY_DETAIL_FAILED: 'GET_PRODUCT_BY_CATEGORY_DETAIL_FAILED',
    GET_LIMIT_PRODUCTS_BY_OPTION_SORT_SUCCESS: 'GET_LIMIT_PRODUCTS_BY_OPTION_SORT_SUCCESS',
    GET_LIMIT_PRODUCTS_BY_OPTION_SORT_FAILED: 'GET_LIMIT_PRODUCTS_BY_OPTION_SORT_FAILED',
    SEARCH_PRODUCT_BY_NAME_SUCCESS: 'SEARCH_PRODUCT_BY_NAME_SUCCESS',
    SEARCH_PRODUCT_BY_NAME_FAILED: 'SEARCH_PRODUCT_BY_NAME_FAILED',
    SEARCH_PRODUCT_BY_NAME_LIMIT_SUCCESS: 'SEARCH_PRODUCT_BY_NAME_LIMIT_SUCCESS',
    SEARCH_PRODUCT_BY_NAME_LIMIT_FAILED: 'SEARCH_PRODUCT_BY_NAME_LIMIT_FAILED',
    SEARCH_PRODUCT_BY_NAME_LIMIT_ERROR_1: 'SEARCH_PRODUCT_BY_NAME_LIMIT_ERROR_1',
    FIND_PRODUCT_BY_NAME_SUCCESS: 'FIND_PRODUCT_BY_NAME_SUCCESS',
    FIND_PRODUCT_BY_NAME_FAILED: 'FIND_PRODUCT_BY_NAME_LIMIT_FAILED',

    // review
    GET_REVIEW_PRODUCT_SUCCESS: 'GET_REVIEW_PRODUCT_SUCCESS',
    GET_REVIEW_PRODUCT_FAILED: 'GET_REVIEW_PRODUCT_FAILED',
    CHANGE_STATE: 'CHANGE_STATE',

    // favourite
    GET_ALL_PRODUCTS_FAVOURITE_SUCCESS: 'GET_ALL_PRODUCTS_FAVOURITE_SUCCESS',
    GET_ALL_PRODUCTS_FAVOURITE_FAILED: 'GET_ALL_PRODUCTS_FAVOURITE_FAILED',
    GET_ALL_PRODUCTS_FAVOURITE_LIMIT_SUCCESS: 'GET_ALL_PRODUCTS_FAVOURITE_LIMIT_SUCCESS',
    GET_ALL_PRODUCTS_FAVOURITE_LIMIT_FAILED: 'GET_ALL_PRODUCTS_FAVOURITE_LIMIT_FAILED',
    CREATE_PRODUCT_FAVOURITE_SUCCESS: 'CREATE_PRODUCT_FAVOURITE_SUCCESS',

    // cart
    GET_ALL_PRODUCTs_IN_CART_BY_USER_SUCCESS: 'GET_ALL_PRODUCTs_IN_CART_BY_USER_SUCCESS',
    GET_ALL_PRODUCTs_IN_CART_BY_USER_FAILED: 'GET_ALL_PRODUCTs_IN_CART_BY_USER_FAILED',
    ADD_PRODUCT_TO_CART_SUCCESS: 'ADD_PRODUCT_TO_CART_SUCCESS',
    ADD_PRODUCT_TO_CART_FAILED: 'ADD_PRODUCT_TO_CART_FAILED',
    DELETE_PRODUCT_IN_SUCCESS: 'DELETE_PRODUCT_IN_SUCCESS',
    DELETE_PRODUCT_IN_FAILED: 'DELETE_PRODUCT_IN_FAILED',

    // firebase
    GET_SIZES_FIREBASE_SUCCESS: 'GET_SIZES_FIREBASE_SUCCESS',
    GET_SIZES_FIREBASE_FAILED: 'GET_SIZES_FIREBASE_FAILED',

    // order
    GET_ALL_ORDERS_BY_USER_SUCCESS: 'GET_ALL_ORDERS_BY_USER_SUCCESS',
    GET_ALL_ORDERS_BY_USER_FAILED: 'GET_ALL_ORDERS_BY_USER_FAILED',
    GET_LIMIT_ORDER_SUCCESS: 'GET_LIMIT_ORDER_SUCCESS',
    GET_LIMIT_ORDER_FAILED: 'GET_LIMIT_ORDER_FAILED',
    GET_ORDER_BY_ID_SUCCESS: 'GET_ORDER_BY_ID_SUCCESS',
    GET_ORDER_BY_ID_FAILED: 'GET_ORDER_BY_ID_FAILED',
    ORDER_FAILED: 'ORDER_FAILED',
    GET_LIST_ORDER_ID_SUCCESS: 'GET_LIST_ORDER_ID_SUCCESS',
    GET_LIST_ORDER_ID_FAILED: 'GET_LIST_ORDER_ID_FAILED',
    CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
    CREATE_ORDER_FAILED: 'CREATE_ORDER_FAILED',
    GET_TOTAL_ORDER_SUCCESS: 'GET_TOTAL_ORDER_SUCCESS',
    GET_TOTAL_ORDER_FAILED: 'GET_TOTAL_ORDER_FAILED',

    // Notification
    GET_NOTIFICATIONS_SUCCESS: 'GET_NOTIFICATIONS_SUCCESS',
    GET_NOTIFICATIONS_FAILED: 'GET_NOTIFICATIONS_FAILED',
    CREATE_NOTIFICATION_SUCCESS: 'CREATE_NOTIFICATION_SUCCESS',
    CREATE_NOTIFICATION_FAILED: 'CREATE_NOTIFICATION_FAILED',

    // report
    GET_MONTHLY_REVENUE_SUCCESS: 'GET_MONTHLY_REVENUE_SUCCESS',
    GET_MONTHLY_REVENUE_FAILED: 'GET_MONTHLY_REVENUE_FAILED',
    GET_DAILY_REVENUE_SUCCESS: 'GET_DAILY_REVENUE_SUCCESS',
    GET_DAILY_REVENUE_FAILED: 'GET_DAILY_REVENUE_FAILED',
    GET_WEEK_REVENUE_SUCCESS: 'GET_WEEK_REVENUE_SUCCESS',
    GET_WEEK_REVENUE_FAILED: 'GET_WEEK_REVENUE_FAILED',
    GET_YEAR_REVENUE_SUCCESS: 'GET_YEAR_REVENUE_SUCCESS',
    GET_YEAR_REVENUE_FAILED: 'GET_YEAR_REVENUE_FAILED',
    GET_TOTAL_REVENUE_SUCCESS: 'GET_TOTAL_REVENUE_SUCCESS',
    GET_TOTAL_REVENUE_FAILED: 'GET_TOTAL_REVENUE_FAILED',
    GET_TOP_10_BEST_SELLING_PRODUCTS_SUCCESS: 'GET_TOP_10_BEST_SELLING_PRODUCTS_SUCCESS',
    GET_TOP_10_BEST_SELLING_PRODUCTS_FAILED: 'GET_TOP_10_BEST_SELLING_PRODUCTS_FAILED',
})

export default actionTypes
