const actionTypes = Object.freeze({
    // login/logout
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILED: 'LOGOUT_SUCCESS',
    CHECK_PERMISSION_SUCCESS: 'CHECK_PERMISSION_SUCCESS',
    CHECK_PERMISSION_FAILED: 'CHECK_PERMISSION_FAILED',

    // user
    CREATE_NEW_USER_SUCCESS: 'CREATE_NEW_USER_SUCCESS',
    CREATE_NEW_USER_FAILED: 'CREATE_NEW_USER_FAILED',
    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',
    FETCH_ALL_PROVINCES_SUCCESS: 'FETCH_ALL_PROVINCES_SUCCESS',
    FETCH_ALL_PROVINCES_FAILED: 'FETCH_ALL_PROVINCES_FAILED',
    FETCH_ALL_GENDER_SUCCESS: 'FETCH_ALL_GENDER_SUCCESS',
    FETCH_ALL_GENDER_FAILED: 'FETCH_ALL_GENDER_FAILED',
    FETCH_ALL_ROLE_SUCCESS: 'FETCH_ALL_ROLE_SUCCESS',
    FETCH_ALL_ROLE_FAILED: 'FETCH_ALL_ROLE_FAILED',
    FETCH_ALL_CODE_BY_TYPE_FAILED: 'FETCH_ALL_CODE_BY_TYPE_FAILED',

    DELTE_USER_SUCCESS: 'DELTE_USER_SUCCESS',
    DELTE_USER_FAILED: 'DELTE_USER_FAILED',
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',
    FETCH_USER_ALLCODE_SUCCESS: 'FETCH_USER_ALLCODE_SUCCESS',
    FETCH_USER_ALLCODE_FAILED: 'FETCH_USER_ALLCODE_FAILED',

    // product
    FETCH_ALL_COLOR_SUCCSESS: 'FETCH_ALL_COLOR_SUCCSESS',
    FETCH_ALL_COLOR_FAILED: 'FETCH_ALL_COLOR_FAILED',

    GET_CATEGORIES_BY_ID_SUCCESS: 'GET_CATEGORIES_BY_ID_SUCCESS',
    GET_CATEGORIES_BY_ID_FAILED: 'GET_CATEGORIES_BY_ID_FAILED',

    FETCH_ALL_LOGO_SUCCESS: 'FETCH_ALL_LOGO_SUCCESS',
    FETCH_ALL_SIZEGIAY_SUCCESS: 'FETCH_ALL_SIZEGIAY_SUCCESS',
    FETCH_GENDER_PRODUCT_SUCCESS: 'FETCH_GENDER_PRODUCT_SUCCESS',
    
    FETCH_ALL_CATEGORIES_SUCCESS: 'FETCH_ALL_CATEGORIES_SUCCESS',
    FETCH_ALL_CATEGORIES_FAILED: 'FETCH_ALL_CATEGORIES_FAILED',

    FETCH_ALL_DISCOUNT_SUCCESS: 'FETCH_ALL_DISCOUNT_SUCCESS',
    FETCH_ALL_BRAND_SUCCESS: 'FETCH_ALL_BRAND_SUCCESS',

    FETCH_ALL_PRODUCTS_SUCCESS: 'FETCH_ALL_PRODUCTS_SUCCESS',
    FETCH_ALL_PRODUCTS_FAILED: 'FETCH_ALL_PRODUCTS_FAILED',
    FETCH_ALL_PRODUCTS_PUBLIC_SUCCESS: 'FETCH_ALL_PRODUCTS_PUBLIC_SUCCESS',
    FETCH_ALL_PRODUCTS_PUBLIC_FAILED: 'FETCH_ALL_PRODUCTS_PUBLIC_FAILED',
    CREATE_NEW_PRODUCT_SUCCESS: 'CREATE_NEW_PRODUCT_SUCCESS',
    CREATE_NEW_PRODUCT_FAILED: 'CREATE_NEW_PRODUCT_FAILED',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILED: 'DELETE_PRODUCT_FAILED',
    FETCH_PRODUCT_BY_ID_SUCCESS: 'FETCH_PRODUCT_BY_ID_SUCCESS',
    FETCH_PRODUCT_BY_ID_FAILED: 'FETCH_PRODUCT_BY_ID_FAILED',
    EDIT_PRODUCT_SUCCESS: 'EDIT_PRODUCT_SUCCESS',
    EDIT_PRODUCT_FAILED: 'EDIT_PRODUCT_FAILED',
    FETCH_ALL_IMAGE_PRODUCT_SUCCESS: 'FETCH_ALL_IMAGE_PRODUCT_SUCCESS',
    FETCH_ALL_IMAGE_PRODUCT_FAILED: 'FETCH_ALL_IMAGE_PRODUCT_FAILED',
    ADD_IMAGE_PRODUCT_SUCCESS: 'ADD_IMAGE_PRODUCT_SUCCESS',
    ADD_IMAGE_PRODUCT_FAILED: 'ADD_IMAGE_PRODUCT_FAILED',
    DELETE_IMAGE_PRODUCT_SUCCESS: 'DELETE_IMAGE_PRODUCT_SUCCESS',
    DELETE_IMAGE_PRODUCT_FAILED: 'DELETE_IMAGE_PRODUCT_FAILED',
    FETCH_DESCRIPTION_PRODUCT_SUCCESS: 'FETCH_DESCRIPTION_PRODUCT_SUCCESS',
    FETCH_DESCRIPTION_PRODUCT_FAILED: 'FETCH_DESCRIPTION_PRODUCT_FAILED',
    ADD_DESCRIPTION_PRODUCT_SUCCESS: 'ADD_DESCRIPTION_PRODUCT_SUCCESS',
    ADD_DESCRIPTION_PRODUCT_FAILED: 'ADD_DESCRIPTION_PRODUCT_FAILED',

})

export default actionTypes
